import {
  PURPLE,
  RED,
  ORANGE,
  BLUE,
  GREEN,
  YELLOW,
  GRAY,
  BROWN,
  PINK,
  TURQUOISE,
} from "./constant";

const INITIAL_PUZZLE_COLOR_1 = [
  [PURPLE, PURPLE, ORANGE, ORANGE, ORANGE, BLUE, BLUE, BLUE],
  [PURPLE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLUE, BLUE],
  [ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE],
  [ORANGE, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, ORANGE],
  [ORANGE, GREEN, GRAY, GRAY, RED, RED, GREEN, YELLOW],
  [ORANGE, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, YELLOW],
  [BROWN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, YELLOW],
  [BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW],
];

const INITIAL_PUZZLE_COLOR_2 = [
  [PURPLE, PURPLE, PURPLE, PURPLE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE],
  [PURPLE, PURPLE, BLUE, PURPLE, ORANGE, PINK, PINK, ORANGE, ORANGE],
  [PURPLE, BLUE, BLUE, GRAY, ORANGE, PINK, ORANGE, ORANGE, ORANGE],
  [PURPLE, BLUE, GRAY, GRAY, ORANGE, PINK, ORANGE, ORANGE, ORANGE],
  [ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE],
  [ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, GREEN, GREEN, GREEN, GREEN],
  [ORANGE, ORANGE, RED, ORANGE, ORANGE, GREEN, GRAY, GRAY, GREEN],
  [ORANGE, RED, RED, RED, ORANGE, GREEN, GRAY, YELLOW, GREEN],
  [ORANGE, ORANGE, RED, ORANGE, ORANGE, YELLOW, YELLOW, YELLOW, GREEN],
];

const INITIAL_PUZZLE_COLOR_3 = [
  [PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE, PURPLE],
  [PURPLE, PURPLE, ORANGE, PURPLE, BLUE, BLUE, BLUE, PURPLE, PURPLE],
  [PURPLE, ORANGE, ORANGE, ORANGE, GREEN, BLUE, BLUE, BLUE, BLUE],
  [PURPLE, PURPLE, ORANGE, GREEN, GREEN, GREEN, GRAY, BLUE, BLUE],
  [PURPLE, PURPLE, PURPLE, PURPLE, GREEN, GRAY, GRAY, GRAY, BLUE],
  [PURPLE, PINK, PINK, PINK, TURQUOISE, BLUE, GRAY, BLUE, BLUE],
  [PURPLE, RED, RED, RED, TURQUOISE, BLUE, BLUE, BLUE, BLUE],
  [PURPLE, RED, RED, RED, TURQUOISE, YELLOW, YELLOW, YELLOW, BLUE],
  [PURPLE, PURPLE, RED, RED, RED, BLUE, BLUE, BLUE, BLUE],
];

const INITIAL_PUZZLE_OPTIONS = [
  INITIAL_PUZZLE_COLOR_1,
  INITIAL_PUZZLE_COLOR_2,
  INITIAL_PUZZLE_COLOR_3,
];

export default INITIAL_PUZZLE_OPTIONS;
