import {
  PURPLE,
  RED,
  ORANGE,
  BLUE,
  GREEN,
  YELLOW,
  GRAY,
  BROWN,
  PINK,
} from "./constant";

const INITIAL_PUZZLE_COLOR_1 = [
  [PURPLE, PURPLE, ORANGE, ORANGE, ORANGE, BLUE, BLUE, BLUE],
  [PURPLE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, BLUE, BLUE],
  [ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE],
  [ORANGE, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, ORANGE],
  [ORANGE, GREEN, GRAY, GRAY, RED, RED, GREEN, YELLOW],
  [ORANGE, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, YELLOW],
  [BROWN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, YELLOW],
  [BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW],
];

const INITIAL_PUZZLE_COLOR_2 = [
  [PURPLE, PURPLE, PURPLE, PURPLE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE],
  [PURPLE, PURPLE, BLUE, PURPLE, ORANGE, PINK, PINK, ORANGE, ORANGE],
  [PURPLE, BLUE, BLUE, GRAY, ORANGE, PINK, ORANGE, ORANGE, ORANGE],
  [PURPLE, BLUE, GRAY, GRAY, ORANGE, PINK, ORANGE, ORANGE, ORANGE],
  [ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, ORANGE],
  [ORANGE, ORANGE, ORANGE, ORANGE, ORANGE, GREEN, GREEN, GREEN, GREEN],
  [ORANGE, ORANGE, RED, ORANGE, ORANGE, GREEN, GRAY, GRAY, GREEN],
  [ORANGE, RED, RED, RED, ORANGE, GREEN, GRAY, YELLOW, GREEN],
  [ORANGE, ORANGE, RED, ORANGE, ORANGE, YELLOW, YELLOW, YELLOW, GREEN],
];

const INITIAL_PUZZLE_OPTIONS = [INITIAL_PUZZLE_COLOR_1, INITIAL_PUZZLE_COLOR_2];

export default INITIAL_PUZZLE_OPTIONS;
